services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: arquea_db
    volumes:
      - arquea_data:/var/lib/postgresql/data

volumes:
  arquea_data:

